dubbo:
  application:
    name: ims-service
  registry:
    address: ${ZOOKEEPER_URL:zookeeper://127.0.0.1:2181}
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.lujiatao.ims.service.impl
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.3.102:10002/ims}
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialization-mode: always
    sql-script-encoding: UTF-8
server:
  port: 8082
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true